name: Deploy

on:
  push:
    tags:
      - "rc-0.0.*"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing deps
        run: npm ci
      - name: Testing
        run: npm test
  deploy:
    needs: test
    env:
      TOKEN: ${{ secrets.OAUTH }}
      ACTOR: ${{ github.actor }}
      TAG_NAME: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.16.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing deps
        run: npm ci
      - name: Ticket update
        run: npm run deploy
      - name: Creating Docker Image
        uses: docker/setup-buildx-action@v2
      - name: Manual docker
        run: docker build . --tag ${{ github.ref_name}}
      - name: Sending comment with docker image tag
        run: node ./scripts/dockerComment.js
